[workspace]
resolver = "2"
members = [
    "src/client",
    "src/common",
    "src/core",
    "src/crew",
    "src/geode",
    "src/spc-test",
    "src/typed-glam",
    "src/typed-glam/codegen",
]

[profile.release]
lto = true
opt-level = 3
