[workspace]
resolver = "2"
members = [
    "src/shared/crucible-math",
    "src/shared/crucible-world",
    "src/util/bevy-autoken",
    "src/util/newtypes",
    "src/util/newtypes-proc",
    "src/util/std-traits",
    "src/util/typed-glam",
    "src/util-gfx/typed-wgpu", "src/client/client-entry",
]
