[workspace]
resolver = "2"
members = ["src/util", "src/server", "src/guest"]

[workspace.dependencies]
crt-marshal = { git = "https://github.com/Radbuglet/crucible-rt.git", rev = "4b91dec0e1c434f69f51a3fe391b665d15054f79" }
crt-marshal-host = { git = "https://github.com/Radbuglet/crucible-rt.git", rev = "4b91dec0e1c434f69f51a3fe391b665d15054f79" }
# crt-marshal = { path = "../crucible-rt/src/marshal" }
# crt-marshal-host = { path = "../crucible-rt/src/marshal-host" }
