[workspace]
resolver = "2"
members = [
	"src/foundation/client",
	"src/foundation/shared",
	"src/game/client",
	"src/game/shared",
	"src/util/typed-glam",
	"src/util/typed-wgpu",
	"src/util/util",
]

[workspace.dependencies]
# Workspace crates
crucible-foundation-client = { path = "src/foundation/client" }
crucible-foundation-shared = { path = "src/foundation/shared" }
crucible-client = { path = "src/game/client" }
crucible-shared = { path = "src/game/shared" }
crucible-util = { path = "src/util/util" }
typed-glam = { path = "src/util/typed-glam" }
typed-wgpu = { path = "src/util/typed-wgpu" }

# Interface dependencies (i.e. dependencies that leak out into the public interface)
bort = { git = "https://github.com/Radbuglet/bort.git", rev = "3ffef4fa7a58a3a5d130c212ceb23bb8c8bb06a0" }
hashbrown = "0.14.0"
log = "0.4.19"
smallvec = "1.11.0"
wgpu = "0.16.2"
winit = "0.28.6"

# Internal dependencies (i.e. dependencies that are only used as implementation details)
anyhow = "1.0.70"
derive-where = "1.2.1"
num-traits = "0.2.15"  # These act mostly like trait aliases and should not be weakened over time.
