[workspace]
resolver = "2"
members = ["src/util", "src/server", "src/guest"]

[workspace.dependencies]
crt-marshal = { git = "https://github.com/Radbuglet/crucible-rt.git", rev = "57846f3184b241962c6f787e2756c2947c8629df" }
crt-marshal-host = { git = "https://github.com/Radbuglet/crucible-rt.git", rev = "57846f3184b241962c6f787e2756c2947c8629df" }
# crt-marshal = { path = "../crucible-rt/src/marshal" }
# crt-marshal-host = { path = "../crucible-rt/src/marshal-host" }
