[workspace]
resolver = "2"
members = [
	"src/foundation/client",
	"src/foundation/shared",
	"src/game/client",
	"src/game/shared",
	"src/util/typed-glam",
	"src/util/typed-wgpu",
	"src/util/util",
]

[workspace.dependencies]
# Workspace crates
crucible-foundation-client = { path = "src/foundation/client" }
crucible-foundation-shared = { path = "src/foundation/shared" }
crucible-client = { path = "src/game/client" }
crucible-shared = { path = "src/game/shared" }
crucible-util = { path = "src/util/util" }
typed-glam = { path = "src/util/typed-glam" }
typed-wgpu = { path = "src/util/typed-wgpu" }

# Interface dependencies (i.e. dependencies that leak out into the public interface)
hashbrown = "0.14.0"
image = "0.24.5"
log = "0.4.19"
smallvec = "1.11.0"
wgpu = "0.17.0"
winit = "0.28.6"

# Internal dependencies (i.e. dependencies that are only used as implementation details)
anyhow = "1.0.70"
bytemuck = "1.10.0"
derive-where = "1.2.1"
num-traits = "0.2.15"  # These act mostly like trait aliases and should not be weakened over time.

[workspace.dependencies.bort]
git = "https://github.com/Radbuglet/bort.git"
rev = "a41045693d08d3195d25ea76753d2afe05fdc6b2"

[profile.dev]
opt-level = 1

[profile.dev.package.image]
opt-level = 3
