[package]
name = "crucible-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
derive-where = { workspace = true }
dummy-waker = "1.1.0"
log = { workspace = true }
smallvec = "1.10.0"
