[package]
name = "typed-glam"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.10.0", features = ["derive"] }
crucible-util = { path = "../util" }
glam = "0.21.3"
num-traits = "0.2.15"
