[package]
name = "crucible-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
derive-where = { workspace = true }
dummy-waker = "1.1.0"
fxhash = "0.2.1"
hashbrown = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
