[package]
name = "crucible-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
hashbrown = { version = "0.11.2", features = ["raw"] }
log = "0.4.14"
once_cell = "1.9.0"

[dev-dependencies]
env_logger = "0.9.0"
futures = { version = "0.3.19" }
