[package]
name = "crucible-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
futures = { version = "0.3.19", features = ["thread-pool"] }
hashbrown = { version = "0.11.2", features = ["raw"] }
log = "0.4.14"
num_cpus = "1.13.1"
once_cell = "1.9.0"

[dev-dependencies]
env_logger = "0.9.0"
