[package]
name = "core"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
futures = { version = "0.3.17", features = ["thread-pool"] }
hecs = "0.6.3"
log = "0.4.14"
num_cpus = "1.13.0"
once_cell = "1.8.0"

[dev-dependencies]
env_logger = "0.9.0"
