[package]
name = "crucible-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.43"
futures = { version = "0.3.17", features = ["thread-pool"] }
hibitset = "0.6.3"
hashbrown = { version = "0.11.2", features = ["raw"] }
log = "0.4.14"
num_cpus = "1.13.0"
once_cell = "1.8.0"

[dev-dependencies]
env_logger = "0.9.0"
