[package]
name = "hash-util"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-where = "1.2.7"
hashbrown = "0.14.5"
newtypes = { version = "0.1.0", path = "../newtypes" }
rustc-hash = "1.1.0"
