use cgmath::Vector3;
use crucible_core::util::meta_enum::EnumMeta;
use crucible_shared::voxel::coord::BlockFace;
use std::fmt::Display;

fn main() {
	println!(r#"// Generated by "shared/examples/gen_mesh_static.rs""#);
	println!();

	for (face, _) in BlockFace::values() {
		let [a, b, c, d] = face.quad_ccw::<i32>();
		println!("// {:?} (index {})", face, face.marshall_shader());
		print_vec(a);
		print_vec(b);
		print_vec(d);
		print_vec(b);
		print_vec(c);
		print_vec(d);
		println!()
	}
}

fn print_vec<T: Display>(vec: Vector3<T>) {
	println!("vec3({}, {}, {}),", vec.x, vec.y, vec.z);
}
