[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
antidote = "1.0.0"
arr_macro = "0.1.3"
bumpalo = "3.10.0"
derive-where = "1.0.0-rc.3"
once_cell = "1.12.0"
thiserror = "1.0.31"
