[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.9.1"
thiserror = "1.0.30"
crossbeam = { version = "0.8.1", features = ["crossbeam-queue"] }
derive-where = "1.0.0-rc.2"
hashbrown = { version = "0.12.0", features = ["raw"] }
log = "0.4.14"
once_cell = "1.9.0"
smallvec = "1.8.0"
