[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.10.0"
crossbeam = { version = "0.8.1", features = ["crossbeam-queue"] }
derive-where = "1.0.0-rc.3"
hashbrown = { version = "0.12.1", features = ["raw"] }
hibitset = { version = "0.6.3", default-features = true }
rustc-hash = "1.1.0"
thiserror = "1.0.31"

[dev-dependencies]
fastrand = "1.7.0"
indexmap = "1.8.2"
