[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.9.1"
crossbeam = { version = "0.8.1", features = ["crossbeam-queue"] }
derive-where = "1.0.0-rc.3"
hashbrown = { version = "0.12.0", features = ["raw"] }
hibitset = "0.6.3"
smallvec = "1.8.0"
thiserror = "1.0.30"

[dev-dependencies]
fastrand = "1.7.0"
