[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
antidote = "1.0.0"
bumpalo = "3.10.0"
derive-where = "1.0.0-rc.3"
once_cell = "1.12.0"
rustc-hash = "1.1.0"
thiserror = "1.0.31"
