[package]
name = "crucible-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bort = { git = "https://github.com/Radbuglet/bort.git", rev = "a4486c4b764162fc29a4277615a16f612aa11073" }
crucible-util = { path = "../util" }
hashbrown = "0.13.1"
log = "0.4.17"
num-traits = "0.2.15"
smallvec = "1.9.0"
typed-glam = { path = "../typed-glam" }
