[package]
name = "crucible-common"
version = "0.1.0"
edition = "2021"

[dependencies]
crucible-util = { path = "../util" }
geode = { git = "https://github.com/Radbuglet/mini-geode.git", rev = "b4834cb7ac888f093797507726b456ab5579c3eb" }
hashbrown = "0.13.1"
log = "0.4.17"
num-traits = "0.2.15"
smallvec = "1.9.0"
typed-glam = { path = "../typed-glam" }
