[package]
name = "crucible-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bytemuck = "1.10.0"
crevice = { version = "0.11.0", features = ["glam"] }
crucible-common = { path = "../common" }
crucible-core = { path = "../core" }
env_logger = "0.9.0"
fastrand = "1.7.0"
futures = "0.3.21"
geode = { path = "../geode" }
log = "0.4.17"
parking_lot = "0.12.1"
thiserror = "1.0.31"
typed-glam = { path = "../typed-glam" }
wgpu = { version = "0.13.1" }
winit = "0.26.1"
