[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
cgmath = "0.18.0"
erupt = "0.19.0"
legion = "0.4.0"
memchr = "2.4.0"
winit = "0.25.0"

[build-dependencies]
glob = "0.3.0"
shaderc = "0.7.2"
winit = "0.25.0"
