[package]
name = "crucible-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
cgmath = "0.18.0"
env_logger = "0.9.0"
geode = { path = "../geode" }
log = "0.4.16"
fastrand = "1.7.0"
wgpu = { version = "0.12.0" }
winit = "0.26.1"
