[package]
name = "crucible-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
cgmath = "0.18.0"
crucible-core = { path = "../core" }
crucible-shared = { path = "../shared" }
env_logger = "0.9.0"
futures = "0.3.19"
glsl-layout = { version = "0.4.0", features = ["cgmath"] }
log = "0.4.14"
wgpu = { version = "0.12.0", features = ["spirv"] }
winit = "0.26.0"

[build-dependencies]
anyhow = "1.0.52"
crucible-core = { path = "../core" }
glob = "0.3.0"
shaderc = "0.7.3"
