[package]
name = "crucible-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bytemuck = "1.10.0"
crevice = { version = "0.11.0", features = ["glam"] }
crucible-common = { path = "../common" }
crucible-util = { path = "../util" }
env_logger = "0.10.0"
fastrand = "1.8.0"
futures = "0.3.25"
geode = { git = "https://github.com/Radbuglet/mini-geode.git", rev = "7b22ab51d01a1b12b6a58f8c416a93b305d5ec75" }
hashbrown = "0.13.2"
image = "0.24.5"
log = "0.4.17"
once_cell = "1.13.0"
thiserror = "1.0.31"
typed-glam = { path = "../typed-glam" }
wgpu = "0.15.0"
winit = "0.28.1"
