[package]
name = "crucible-math"
version = "0.1.0"
edition = "2021"

[dependencies]
crucible-utils = { version = "0.1.0", path = "../../util/crucible-utils" }
num-traits = "0.2.19"
typed-glam = { version = "0.1.0", path = "../../util/typed-glam" }
